### ISSUE TITLE
Include `structured` data inside /addresses response

### ISSUE THREAD

**Issue by mjlai3** [mountain-pass/addressr#143]
Hi there! Loving the package so far @tompahoward 😄.

Would you please consider including the `structured` data in the response for the `/addresses?q=` endpoint?

This would be incredibly helpful for auto completing form fields without having to call an additional `/addresses/{id}` to get the full details of the address.

For example
```javascript
function mapToSearchAddressResponse(foundAddresses) {
  return foundAddresses.hits.hits.map(h => {
    return {
      structured: h._source.structured.structured, // <- add this
      sla: h._source.sla,
      score: h._score,
      links: {
        self: {
          href: h._id
        }
      }
    };
  });
}
```

**Comment by tompahoward** [comment]
Thanks for the suggestion. We'll need to assess the performance impacts, but otherwise we have no objection to doing this.

**Comment by tompahoward** [comment]
@mjlai3 how are you using the structured address?

**Comment by mjlai3** [comment]
@tompahoward That's great to hear!

We're using the typical address fields from the structured address for our form, which are:
- Flat number
- Flat type
- Street number
- Street name
- Street type
- Suburb (locality)
- Postcode
- State

**Comment by tompahoward** [comment]
@mjlai3 yes, but what are you doing with it? Are you storing it, are you displaying it, are you printing it, etc?

**Comment by mjlai3** [comment]
Yep that's right, we're first displaying it to the user, then storing it, and then lastly sending it to a third party which requires an address for the user.

**Comment by tompahoward** [comment]
Cool. For display and for third party, you're best off using the multi-line address (mla). This is the "standard" 3 or 4 line address that people are used to.

If you want to display a map with it, use `latitude` and `longitude` of the default `geocoding.geocodes`. The default one is the one with `"default": true`.

For storage, or you're best off **ONLY** storing the `<BASE_URL>/addresses/{id}`. This is because addresses for a location can and do change, but their URL won't. For example, not too long ago, "The Entrance Road" was renamed "The Central Coast Hwy". All the addresses on "The Entrance Road" changed, but their IDs didn't (and neither did their URL).

Whenever you need to display, print or send the address to a third party (that doesn't have access to `<BASE_URL>/addresses/{id}`), your system retrieves  `<BASE_URL>/addresses/{id}` and then displays, prints or sends the latest version of that address.

**Comment by tompahoward** [comment]
and this is why the `/addresses?q=` endpoint doesn't include the structured address.

**Comment by mjlai3** [comment]
Thanks for the insights @tompahoward, that was incredibly helpful. 

Interestingly for our use case we allow non Australian addresses too, so storing all addresses consistently in the structure of street address, suburb/state, and postcode rather than just an id was preferred. 

Because of this, we were looking for ways to get the structured address from the `/addresses?q=` endpoint without the extra call to `/addresses/{id}`.

If this use case is not something Addressr is meant to support, that is totally understandable. Would you consider allowing an optional query param to include the structured address in the response?

**Comment by tompahoward** [comment]
@mjlai3 , sorry it's taken us so long to get back to you on this. 
The new `addressr-server-2` has HTTP caching features that gives it blindingly fast performance. 
Let us know if it's not fast enough.
